export const projects = [
  {
    name: "Portfolio Website",
    category: "Personal Project",
    description: "Built with Next.js and Tailwind CSS.",
    techStack: ["Next.js, Tailwind, TypeScript"],
    github: "https://github.com/username/portfolio",
    preview: "https://example.com",
    image: "https://example.com",
  },
  {
    name: "Useless Facts Club",
    category: "Side Project",
    desc: "A fun space for sharing and discovering useless facts, built with Next.js, Tailwind, and Postgres.",
    techStack: ["Next.js, Node.js, PostgreSQL"],
    github: "https://github.com/genta-bahana-nagari/useless-facts-club",
    preview: "https://useless-facts-club.vercel.app/",
    image: "https://example.com",
  },
  {
    name: "SIJA Phone",
    category: "Learning Project",
    desc: "Simple group project about Phone Store, featured with RBAC, checkout and shipping feature.",
    techStack: ["Laravel, PHP, MySQL"],
    github: "https://github.com/genta-bahana-nagari/phone_store",
    preview: "https://sijaphone.gentabahana.me",
    image: "https://example.com",
  },
  {
    name: "Safewalk",
    category: "Learning Project",
    desc: "IoT-based safety stick to help blind people navigate safely. Built with NodeMCU and HCSR04 sensors with calibrated accuracy.",
    techStack: ["C++, NodeMCU"],
    github: "https://github.com/genta-bahana-nagari/safewalk-project",
    preview: null,
    image: "https://example.com",
  },
  {
    name: "Inventory System",
    category: "Learning Project",
    desc: "Laravel based inventory system with high reliability and data accuracy.",
    techStack: ["Laravel, PHP, MySQL"],
    github: "https://github.com/genta-bahana-nagari/sinvent24",
    preview: null,
    image: "https://example.com",
  },
  {
    name: "ESP32 Camera",
    category: "Learning Project",
    desc: "Built for P5 school event. Perfect combination of price-friendly components and innovations.",
    techStack: ["C++, NodeMCU"],
    github: "https://github.com/genta-bahana-nagari/ESP32_Cam_Servo",
    preview: null,
    image: "https://example.com",
  },
];