export const projects = [
  {
    name: "Useless Facts Club",
    category: "Side Project",
    description: "A fun space for sharing and discovering useless facts, built with Next.js, Tailwind, and Postgres.",
    techStack: ["Next.js, Node.js, PostgreSQL"],
    github: "https://github.com/genta-bahana-nagari/useless-facts-club",
    preview: null,
    image: "/images/projects/Facts_Club.png",
  },
  {
    name: "SIJA Phone",
    category: "Learning Project",
    description: "Simple group project about Phone Store, featured with RBAC, checkout and shipping feature.",
    techStack: ["Laravel, PHP, MySQL"],
    github: "https://github.com/genta-bahana-nagari/phone_store",
    preview: null,
    image: "/images/projects/SIJA_Phone.png",
  },
  {
    name: "Safewalk",
    category: "Learning Project",
    description: "IoT-based safety stick to help blind people navigate safely. Built with NodeMCU and HCSR04 sensors with calibrated accuracy.",
    techStack: ["C++, NodeMCU"],
    github: "https://github.com/genta-bahana-nagari/safewalk-project",
    preview: null,
    image: "/images/projects/Safe_Walk.jpg",
  },
  {
    name: "Inventory System",
    category: "Learning Project",
    description: "Basic inventory system with high reliability and data accuracy.",
    techStack: ["Laravel, PHP, MySQL"],
    github: "https://github.com/genta-bahana-nagari/sinvent24",
    preview: null,
    image: "/images/projects/Inventory_System.png",
  },
  {
    name: "ESP32 Camera",
    category: "Learning Project",
    description: "Built for class showcase in school events. Perfect combination of price-friendly components and innovations.",
    techStack: ["C++, NodeMCU"],
    github: "https://github.com/genta-bahana-nagari/ESP32_Cam_Servo",
    preview: null,
    image: "/images/projects/Esp_Cam.jpg",
  },
];