export const projects = [
  {
    name: "Useless Facts Club",
    category: "Side Project",
    status: "Under Development",
    description: "A fun space for sharing useless facts, giving votes, and check your leaderboard.",
    techStack: ["Next.js", "Node.js", "PostgreSQL"],
    github: "https://github.com/genta-bahana-nagari/useless-facts-club",
    preview: "https://useless-facts-club.vercel.app/",
    image: "/images/projects/Facts_Club.png",
  },
  {
    name: "SIJA Phone",
    category: "Group Project",
    status: null,
    description: "Simple group project about Phone Store, featured with RBAC, checkout and shipping feature.",
    techStack: ["Laravel", "Tailwind", "MySQL"],
    github: "https://github.com/genta-bahana-nagari/sija-phone",
    preview: null,
    image: "/images/projects/SIJA_Phone.png",
  },
  {
    name: "SIJA Kerja",
    category: "Learning Project",
    status: null,
    description: "This project is based on the theme of Practical Exam, an information system for internship applications.",
    techStack: ["Laravel", "Livewire", "MySQL"],
    github: "https://github.com/genta-bahana-nagari/sija-kerja",
    preview: null,
    image: "/images/projects/SIJA_Kerja.png",
  },
  {
    name: "Inventory System",
    category: "Learning Project",
    status: null,
    description: "Basic inventory system with high reliability and data accuracy. Used as my Laravel learning fundamental.",
    techStack: ["Laravel", "Bootstrap", "MySQL"],
    github: "https://github.com/genta-bahana-nagari/sinvent24",
    preview: null,
    image: "/images/projects/Inventory_System.png",
  },
];